# Generated by Django 2.1.3 on 2020-03-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('employee_status', models.CharField(choices=[('Trainee', 'Trainee'), ('Probation', 'Probation'), ('Permanent', 'Permanent'), ('NoticePeriod', 'NoticePeriod'), ('Contract', 'Contract')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=60)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widow', 'Widow'), ('Divorced', 'Divorced')], max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('stage', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('price_unit', models.FloatField()),
                ('total', models.FloatField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.JobTitle'),
        ),
    ]
